---
title: "Mini Project 3"
author: "Sam Ellinwood"
date: "11/8/2017"
output: html_document
---

```{r, message = FALSE}
library(tidyverse)
library(mdsr)
library(RMySQL)
library(viridis)
db <- dbConnect_scidb(dbname = "imdb")
```

```{r}
#Create a table of sequels
sql_tbl <- db %>%
  dbGetQuery(
  "SELECT DISTINCT movie_link.movie_id AS sequel_id, linked_movie_id AS original_id, link_type_id, production_year AS sequel_year, title AS sequel_title  
  FROM imdb.movie_link
  JOIN aka_title ON movie_link.movie_id = aka_title.movie_id
  WHERE movie_link.movie_id > 0
    AND aka_title.kind_id = 1
    AND (link_type_id = 1);
")
```

```{r}
#Create a table of originals (movies linked to sequels)
orig_tbl <- db %>%
  dbGetQuery(
    "SELECT movie_id AS original_id, production_year AS original_year, title AS original_title
  FROM imdb.aka_title
  WHERE production_year IS NOT NULL
    AND movie_id > 0;
")
```

```{r}
#Create the full table
full_tbl <- sql_tbl %>%
  left_join(orig_tbl, by = "original_id") %>%
  unique() 
```


```{r}
#Create the data graphic
full_tbl %>%
  filter(sequel_year > 1950 & sequel_year < 2017 & original_year != "NA") %>%
  group_by(sequel_year) %>%
  summarize("count" = n(),
            "difference" = mean(sequel_year - original_year)) %>%
ggplot(aes(x = sequel_year, y = count)) +
  geom_point(aes(color = difference)) +
  geom_smooth(se = FALSE) +
  scale_color_viridis(option = "inferno")
```
